# Generated by Django 4.0.4 on 2022-05-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('ru', 'RUB'), ('us', 'USD')], default='ru', max_length=2),
        ),
    ]
